export const tags = [
	"American",
	"Poultry",
	"Asian",
	"Pastas",
	"Mexican",
	"Middle Eastern",
	"Pies And Tarts",
	"Salads And Dressings",
	"Bison",
	"Italian",
	"Greek",
	"Grains And Rice",
	"Anchovy",
	"Vietnamese",
	"Chinese Egg Noodle",
	"Mediterranean",
	"Korean",
	"Meatballs",
	"Noodles",
	"Jewish",
	"Indian",
	"Dumplings",
	"Project",
	"Sausages",
	"Seafood",
	"One Pot",
	"Corn Tortilla",
	"African",
	"Turkish",
	"Austrian",
	"German",
	"Meat",
	"Brussels Sprout",
	"Bell Pepper",
	"Butter",
	"Canola Oil",
	"Soups And Stews",
	"Cilantro",
	"Casseroles",
	"Ground Lamb",
	"Shiitake",
	"Spelt",
	"Noodle",
	"Fennel",
	"Chicken Fat",
	"Kimchi",
	"Cilantro Leaves",
	"Corn",
	"Gruyere",
	"Side Dish",
	"Fall",
	"Rotisserie Chicken",
	"Rosemary",
	"Olives",
	"Leek",
	"Mint",
	"Ground Pork",
	"Chile Crisp",
	"White Wine Vinegar",
	"Scallion",
	"Cinnamon Stick",
	"Parsley",
	"Potato",
	"Phyllo",
	"Ritz Cracker",
	"Pearl Couscous",
	"Walnut",
	"Lime",
	"Radish",
	"Salmon",
	"Pepper",
	"Oyster Sauce",
	"Puff Pastry",
	"Passover",
	"Red Onion",
	"Nam Pla",
	"Quinoa",
	"Tamarind Sauce",
	"Tortilla Chip",
	"Thyme",
	"High Fiber",
	"Prosciutto",
	"Low Carb",
	"Pistachio",
	"Unsweetened Coconut Milk",
	"Christmas",
	"New Year’s Day",
	"Super Bowl",
	"Hanukkah",
	"Winter",
	"New Year’s Day",
	"Thanksgiving",
	"Tailgate",
	];